apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bimservice-deployment
spec:
  selector:
    matchLabels:
      app: bimservice
  replicas: 1
  template:
    metadata:
      labels:
        app: bimservice
    spec:
      containers:
      - name: bim-service
        image: winsonchu/bim-service_web
        ports:
        - containerPort: 4004 
      imagePullSecrets:
        - name: my-pull-secret #make sure this name matches with the "name" in your mysecret.yaml file
